######################################################################
# Automatically generated by qmake (1.07a) Thu Mar 22 23:50:16 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += basepair.ui.h
INTERFACES += basepair.ui
SOURCES += main.cpp
